name: ieu-gwas-db-demo
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - automake
  - pandas
  - requests
  - jupyterlab
  - r-tidyverse
  - r-curl
  - r-devtools
  - r-irkernel
